# Generated by Django 3.0.8 on 2020-07-19 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaVerificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonsocial', models.CharField(max_length=119)),
                ('rfc', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecontacto', models.CharField(max_length=119)),
                ('emailcontacto', models.EmailField(max_length=254)),
                ('telefonocontacto', models.CharField(max_length=15)),
                ('etiqueta', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgc.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreacion', models.DateTimeField(auto_now=True)),
                ('descripcionservicio', models.TextField()),
                ('moneda', models.CharField(choices=[('MXN', 'PESOS MEXICANOS'), ('USD', 'DOLARES')], max_length=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=17)),
                ('riesgoimparcialidad', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgc.Cliente')),
                ('creadopor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadVerificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=119)),
                ('acronimo', models.CharField(max_length=119)),
                ('rfc', models.CharField(max_length=50)),
                ('directorgeneral', models.CharField(max_length=119)),
                ('telefono', models.CharField(max_length=119)),
                ('correo', models.EmailField(max_length=119)),
                ('domicilio', models.CharField(max_length=119)),
                ('imagen', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Verificador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=119)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechafinalizacion', models.DateTimeField()),
                ('fechaprogramada', models.DateField()),
                ('fecharecibo', models.DateField()),
                ('objetivoverificacion', models.TextField()),
                ('condicionevisita', models.TextField(verbose_name='Condiciones para realizar antes de la verificacion')),
                ('quiposeguridad', models.TextField(default='El requerido por la empresa')),
                ('documental', models.BooleanField(default=False)),
                ('fisica', models.BooleanField(default=False)),
                ('entrevistapersonal', models.BooleanField(default=False)),
                ('atenderavisita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgc.Contacto')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgc.Cotizacion')),
                ('creadopor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgc.Verificador')),
            ],
            options={
                'ordering': ['fechacreacion'],
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=119)),
                ('codigo', models.CharField(max_length=50)),
                ('acreditacion', models.CharField(max_length=110)),
                ('vigenciadictamen', models.CharField(max_length=30)),
                ('tipoproceso', models.CharField(max_length=30)),
                ('tiemporealizaciondictamenes', models.CharField(max_length=30)),
                ('vigenciacotizacion', models.CharField(max_length=50)),
                ('gerentetecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normagerentetecnico', to='sgc.Verificador')),
                ('gerentetecnicosustituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normagerentesustituto', to='sgc.Verificador')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPropuestaEconomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaverificar', models.CharField(max_length=119)),
                ('costounitario', models.DecimalField(decimal_places=2, max_digits=17)),
                ('costototal', models.DecimalField(decimal_places=2, max_digits=17)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgc.Cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Fc00',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordentrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgc.OrdenTrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=119)),
                ('numero', models.PositiveIntegerField()),
                ('colonia', models.CharField(max_length=119)),
                ('cp', models.PositiveIntegerField()),
                ('ciudad', models.CharField(max_length=119)),
                ('interior', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgc.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Dictamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('actaverificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgc.ActaVerificacion')),
                ('creadopor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActaEvaualcionConformidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('fechaenvioelementosverificar', models.DateTimeField()),
                ('medianteenvio', models.CharField(max_length=119)),
                ('fechaconfirmado', models.DateTimeField()),
                ('medianteconfirmado', models.CharField(max_length=119)),
                ('ordentrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgc.OrdenTrabajo')),
            ],
        ),
    ]
